package sanguine.strategies;

import sanguine.controller.PlayerActionListener;

/**
 * Allows an object (specifically AIPlayer) to receive a reference to the
 * PlayerActionListener that should handle its actions.
 */
public interface ActionPublisher {
  /**
   * Registers the listener that will receive player action events generated by this object.
   *
   * @param listener the controller
   */
  void setActionListener(PlayerActionListener listener);
}